---
title: "MVO_final"
author: "Margaret Liu"
date: "2023-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##port optimization 

##but first, download all these damn libraries

```{r}
library(quantmod)
library(PerformanceAnalytics)
library(PortfolioAnalytics)
library(foreach)
library(DEoptim)
library(iterators)
library(fGarch)
library(Rglpk)
library(quadprog)
library(ROI)
library(ROI.plugin.glpk)
library(ROI.plugin.quadprog)
library(ROI.plugin.symphony)
library(pso)
library(GenSA)
library(corpcor)
library(testthat)
library(nloptr)
library(MASS)
library(robustbase)
```


```{r cars}


tickers <- c("TSM", "PFE", "CMCSA", "HMC", "GMAB", "NKE", "PSA", "DLR") 

portfolioPrices <- NULL
for(ticker in tickers) {
  portfolioPrices <- cbind(portfolioPrices,
                           getSymbols.yahoo(ticker, from='2005-01-03', periodicity = 'monthly', auto.assign=FALSE)[,4]) #could change this 
}

portfolioReturns <- na.omit(ROC(portfolioPrices))

portf <- portfolio.spec(colnames(portfolioReturns))

#objectvies and constraints 

portf <- add.constraint(portf, type="weight_sum", min_sum=1, max_sum=1.) #long-only, no shorts 
portf <- add.constraint(portf, type="box", min=0.01, max=.99) #each indiv asset canot be less thatn 10% and cannot exeed 40%

#max return, min risk, no givens 
portf <- add.objective(portf, type="return", name="mean") #max return = mean 
portf <- add.objective(portf, type="risk", name="StdDev") #min isk  = stdDev

#simple solver 
optPort <- optimize.portfolio(portfolioReturns, portf, optimize_method = "random", trace=TRUE)

#visualize weights of THE optimal portfolio 

#optimally allocated weights to match our objective: max return, min risk 
chart.Weights(optPort)


#visualize in a efficient frontier 
ef <- extractEfficientFrontier(optPort, match.col = "StdDev", n.portfolios = 25,
                         risk_aversion = NULL)

chart.EfficientFrontier(ef,
                        match.col = "StdDev", n.portfolios = 25, xlim = NULL, ylim = NULL,
                        cex.axis = 0.8, element.color = "darkgray", main = "Efficient Frontier",
                        RAR.text = "SR", rf = 0, tangent.line = TRUE, cex.legend = 0.8,
                        chart.assets = TRUE, labels.assets = TRUE, pch.assets = 21,
                        cex.assets = 0.8)
```

